### PR TITLE
Copy changes to right branch for deployment.

### PR DESCRIPTION
**Pull request by johnmlee101**
Copying over from https://github.com/Expensify/react-native/pull/45

# Upstream PR Link
https://github.com/facebook/react-native/pull/36428

## Summary
For https://github.com/Expensify/App/issues/15310

## Changelog

[CATEGORY] [TYPE] - Message

### CODE REVIEW

**Comment by johnmlee101** [comment]
@roryabraham this is fine, and I will deploy to the new branch [Expensify-0.71.2-alpha.4](https://github.com/Expensify/react-native/tree/Expensify-0.71.2-alpha.4) once this is done, correct?

**Comment by johnmlee101** [comment]
Bump!

**Comment by roryabraham** [comment]
@johnmlee101 Sorry, have been OOO. I think we need to be targeting https://github.com/Expensify/react-native/tree/ExpensifyRC1-0.72.0-alpha.0

**Comment by roryabraham** [comment]
More importantly though, we shouldn't merge any changes that we don't view as having a high likelihood of being merged upstream. Judging by the [latest comment in the upstream PR](https://github.com/facebook/react-native/pull/36428#issuecomment-1560116244), there are some changes needed. This fix appears unlikely to be merged as-is

**Pull request closed without merging**
