### PR TITLE
feat: fix show soft input on focus behavior (#35244)

### PR DESCRIPTION
**Pull request by zzz0108**
# Upstream PR Link
https://github.com/facebook/react-native/pull/35244

I'm cherry-picking [this commit](https://github.com/facebook/react-native/commit/7425c24cbe66ec743794b6ffc4cc1a653e821dde) from the React Native upstream repo, `main` branch. This is tagged for the `0.72.0` release so should be out soon.

This is needed so we can move forward with [this issue](https://github.com/Expensify/App/issues/10731#issuecomment-1507524395).

## Summary

The `showSoftInputOnFocus` of `TextInput` is not working properly. When we set `showSoftInputOnFocus` to false and subsequently to `true`, it fails to open the keyboard, we have to re-focus on the input in order for the keyboard to show. It's expected that the keyboard will be opened as soon as  `showSoftInputOnFocus` becomes `true`. This happens on iOS only.
Reference in React Native doc: https://reactnative.dev/docs/textinput#showsoftinputonfocus.

## Changelog

[iOS] [Fixed] - Fix issue where keyboard does not open when `TextInput` `showSoftInputOnFocus` changes from `false` to `true`

## Test Plan

I've made a clean `create-react-native-app` repo to demonstrate this https://github.com/christianwen/reduced-rn-app.
Here's the steps:
1. Clone https://github.com/christianwen/reduced-rn-app
2. Run `yarn install`
3. Run `cd ios`, then `pod install`, then `cd ..`
4. Run `yarn ios`
5. See the text input on the top of the screen, it can be observed that the keyboard does not open because `showSoftInputOnFocus` is `false`, 3 seconds later it becomes `true` due to a `setTimeout` that is used
Screenshot 2022-11-07 at 23 39 50

https://user-images.githubusercontent.com/21312517/200366099-db8626a6-1a31-4bfc-862c-2e37a8b35a3f.mov

However, it can be seen that the keyboard does not open even though `showSoftInputOnFocus` becomes `true`
6. Now add the change in this PR to `Libraries/Text/TextInput/RCTBaseTextInputView.m`
7. Run `yarn ios` again
8. Now verify the step 5 again, the keyboard will open automatically when `showSoftInputOnFocus` becomes `true`

https://user-images.githubusercontent.com/21312517/200363910-726716b1-e76d-420b-848d-a98747868db9.mp4

The reason why I created a fresh RN repo instead of using `rn-tester` app is because the `showSoftInputOnFocus` example is not working in `rn-tester` app for some reasons (it shows the keyboard even though `showSoftInputOnFocus` is `false` in the example).

Regarding the code, it's similar to the fix for `keyboardType` in https://github.com/facebook/react-native/commit/8baaacb66458dd706421fcbc1fc1934cd1ebbb94.

Screenshot 2022-11-07 at 23 36 41

### CODE REVIEW

**Comment by Santhosh-Sellavel** [comment]
@christianwen Can you follow the PR tempate and update it.

**Comment by zzz0108** [comment]
> @christianwen Can you follow the PR template and update it.

@Santhosh-Sellavel done! thanks for highlighting

**Comment by Santhosh-Sellavel** [comment]
cc: @iwiznia

**Review by Santhosh-Sellavel — DISMISSED** [review]
LGTM, all yours @iwiznia.

**Comment by Santhosh-Sellavel** [comment]
@iwiznia bump again!

**Comment by iwiznia** [comment]
Yes yes, I am on it, I just don't work on weekends 😄

**Review by iwiznia — DISMISSED** [review]

**Comment by Santhosh-Sellavel** [comment]
Ah, it was on weekend right 😅 !

**Comment by iwiznia** [comment]
This failed 
image

**Comment by Santhosh-Sellavel** [comment]
cc: @christianwen

**Comment by Santhosh-Sellavel** [comment]
@iwiznia Reinitiate the workflow, also changes didn't touch anything specific to android

**Comment by iwiznia** [comment]
ok, re-running. If it fails, let's try merging main to this branch

**Comment by iwiznia** [comment]
It failed again... @christianwen can you try merging main into this branch please?

**Comment by zzz0108** [comment]
@iwiznia it says "Already up to date." when I try to merge main into my branch. Also the latest update on main was from Jan 19, while I branched out from main only a few days ago so I think my branch is up to date.

**Comment by iwiznia** [comment]
Ah then no idea, can you investigate the failure?

**Comment by zzz0108** [comment]
@iwiznia hmm I'm not familiar to the CI setup here and also I don't think we're touching any Android part in this PR.

Just confirming is 'main' the right branch to merge to? I see some recent merged PRs are merged into release branches, not main. For example this PR https://github.com/Expensify/react-native/pull/46.

**Comment by iwiznia** [comment]
hmmm good question, maybe not? I am not sure... @roryabraham I see you on that other PR, is `[Expensify:Expensify-0.71.2-alpha.2](https://github.com/Expensify/react-native/tree/Expensify-0.71.2-alpha.2) f` the right branch to target?

**Comment by roryabraham** [comment]
@iwiznia Now the correct branch to target should be ExpensifyRC1-0.72.0-alpha.0

**Comment by Santhosh-Sellavel** [comment]
@christianwen can you change the target branch then?

**Comment by zzz0108** [comment]
If `ExpensifyRC1-0.72.0-alpha.0` is the correct branch then the commit I intended to cherry-pick here is already included in that branch. But I see we're not using the `0.72.0` version in our `Expensify/App`, we're using `0.71.2`, so I doubt `ExpensifyRC1-0.72.0-alpha.0` is the right branch if we want the commit to be used by the app. @roryabraham Am I missing something?

**Comment by roryabraham** [comment]
We are working to upgrade E/App to 0.72.0 as soon as we can.

**Pull request closed without merging**
