### PR TITLE
fix(android): selection menu missing controlled textinput

### PR DESCRIPTION
**Pull request by hannojg**
# Upstream PR Link

- https://github.com/facebook/react-native/pull/36663#issuecomment-1485568244

## Summary

This PR solves this bug: 

- https://github.com/Expensify/App/issues/8349

So the bug wasn't a bug caused by Expensify App code, but was really a native bug that existed within react native. 

## Changelog

[ANDROID] [FIXED] - Selection menu missing when TextInput uses controlled selection prop

## Test Plan

Manually test text inputs

### CODE REVIEW

**Comment by parasharrajat** [comment]
I will try to trace the code and understand the impact of change. Though, RN codebase complexity is very high so my odds are less :smile:

**Comment by parasharrajat** [comment]
Responsible commit https://github.com/hannojg/react-native/commit/29f3f5529827579101f0d8bd6afe72f1cb0caeca

**Comment by roryabraham** [comment]
@hannojg can you update this to target Expensify-0.71.2-alpha.3 ?

**Comment by hannojg** [comment]
@roryabraham updated!

**Comment by parasharrajat** [comment]
There is a problem from this solution as per the upstream PR.

**Comment by hannojg** [comment]
Closed in favour of #55

**Pull request closed without merging**
