### PR TITLE
[iOS] fix: reduce cursor size for multiline(TextInput)

### PR DESCRIPTION
**Pull request by soumyajit4419**
# Upstream PR Link

[Upstream PR](https://github.com/facebook/react-native/pull/36484)

## Summary

[Issue #15640](https://github.com/Expensify/App/issues/15640)

In Chat - Cursor in the second and following lines touches the symbols of the previous line

## Changelog

[iOS] [Fixed] - Fix cursor height in RCTUITextView

## Test Plan

The new UI after the code changes.
https://user-images.githubusercontent.com/46092576/226199938-78400fe7-1f25-4522-8ab9-b312c1197d5b.mov

### CODE REVIEW

**Review by alex-mechler — APPROVED** [review]
Changes work well, waiting on automated tests
image

**Review by alex-mechler — APPROVED** [review]
@soumyajit4419 Can you change the base branch of this from `main` to `v0.71.2-alpha.3`

**Review by alex-mechler — CHANGES_REQUESTED** [review]
Whoops, was meant to be a request changes

**Comment by soumyajit4419** [comment]
@alex-mechler I have changed the base branch `main` to `v0.71.2-alpha.3`

**Comment by alex-mechler** [comment]
Holding off on this since there was another regression found, and thus this was reverted in the base RN

**Comment by alex-mechler** [comment]
Going to close this out since we have reopened the issue for proposals.

**Pull request closed without merging**
