### PR TITLE
feat: add `verticalScrollbarPosition` prop to `ScrollView`

### PR DESCRIPTION
**Pull request by hannojg**
## Summary

This is a temporary addition to help circumvent a bug on android. Long term we want to fix the root cause of the problem.

- RN issue: https://github.com/facebook/react-native/issues/35350
- Expensify issue: https://github.com/Expensify/App/issues/11321#issuecomment-1317770412

## Changelog

[Android] [Added] - add `verticalScrollbarPosition` prop (can be `left` or `right`)

### CODE REVIEW

**Review by mountiny — APPROVED** [review]
This looks good to me, we would need to do a release of our branch. @roryabraham is that something you could help with?

**Review by Beamanator — APPROVED** [review]
Also looks good to me!

**Comment by mountiny** [comment]
Tests were passing.

**Comment by AndrewGable** [comment]
I'm going to publish this under `expensify/react-native@0.70.4-alpha.2` Which will continue to use react native 0.70.4, but just with this commit added on.

**Pull request merged**
